### ISSUE TITLE
Implement cloudamqp instead of http

### ISSUE THREAD

**Issue by kesar** [NebulaProtocol/dfuse-feeder#1]
Right now when a messages from the webservices is detected, we post it to a backend. It would be great to use a queue system like cloudamqp

**Comment by NebulaBounty** [comment]
---
### Nebula Bounty open! 
Author: **kesaritooooo**
Reward: **0.0001 EOS**
Link: https://app.nebulaprotocol.com/explorer/9c598a60-df7d-11e8-a9bf-f713400f1d95

**Comment by NebulaBounty** [comment]
---
### Nebula Bounty closed! 
Worker: **kesaritooooo**
Reward: **2.0000 EOS**
